spring:
  application:
    name: event-collector
  kafka:
    bootstrap-servers: localhost:29092
    listener:
      ack-mode: batch
    consumer:
      group-id: avro-reactive-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
        acks: all
        enable.idempotence: true
  flyway:
    password: postgres
    url: jdbc:postgresql://localhost:5432/ourcode
    user: postgres
    enabled: false
    baseline-on-migrate: true
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: event_keyspace
    local-datacenter: datacenter1
    username: cassandra
    password: cassandra
    schema-action: create-if-not-exists
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/ourcode