@startuml

actor IOT_Devices
participant "Kafka Topic: events.in" as KTI
participant EventConsumer
database Cassandra
participant "Kafka Topic: device-ids" as KTD

IOT_Devices -> KTI: send telemetry
KTI -> EventConsumer: handle(List<ConsumerRecord>)
activate EventConsumer
EventConsumer -> Cassandra: saveAll(events)
activate Cassandra
Cassandra --> EventConsumer
deactivate Cassandra
EventConsumer --> KTD: send unique device-ids
deactivate EventConsumer
@enduml